check50:
  files: &check50_files
    - !exclude "*"
    - !include "substitution.py"
          
  checks:
    hello world:
      - run: python3 substitution.py encrypt
        stdin:
          - qwertyuiopasdfghjklzxcvbnm
          - helloworld
        stdout: itssgvgksr
    No Arguments:
      - run: python3 substitution.py 
        stdout: Usage substitution.py encrypt/decrypt
        exit: 1
    Too many arguments:
      - run: python3 substitution.py 2 3 5
        stdout: Too many arguments.
        exit: 1
    Mixed case Encrypt:
      - run: python3 substitution.py enCRypt
        stdin:
          - qwertyuiopasdfghjklzxcvbnm
          - helloworld
        stdout: itssgvgksr
    Misspelled Encryyyypt:
      - run: python3 substitution.py encryyyypt
        stdout: Did you enter encrypt or decrypt as the second argument?
        exit: 1
    Key too short:
      - run: python3 substitution.py encrypt
        stdin: 
          - qwertyuasdf
        stdout: Invalid key length.
        exit: 1
    Key too long:
      - run: python3 substitution.py encrypt
        stdin: 
          - qwertyuasdfqwertyuasdfqwertyuasdf
        stdout: Invalid key length.
        exit: 1
    Duplicate letters in key:
      - run: python3 substitution.py encrypt 
        stdin: 
          - qwertyuiopasdfghjklzxcvbnn
        stdout: Duplicate letters found in key.
    Accepts mixed case:
      - run: python3 substitution.py encrypt
        stdin:
          - qwertyuiopasdfghjklzxcvbnm
          - HeLLoWorLD
        stdout: ItSSgVgkSR
    Accepts upper and lower case numbers specials chars:
      - run: python3 substitution.py encrypt
        stdin:
          - qwertyuiopasdfghjklzxcvbnm
          - Upp3rL0. wer$p3c14l-l33t
        stdout: Xhh3kS0. vtk$h3e14s-s33z
    Accepts mixedcase key:
      - run: python3 substitution.py encrypt
        stdin:
          - QWERTYUIOPasdfghjklZXCVBNM
          - HelloWorld!
        stdout: ItssgVgksr!
    Decrypt names:
      - run: python3 substitution.py decrypt
        stdin:
          - QWERTYUIOPasdfghjklZXCVBNM
          - Hqkatk! Tkoe! Doeiqts! Tziqf! Egffgk! Voss! Wkoqf!
        stdout: Parker! Eric! Michael! Ethan! Connor! Will! Brian!
    Decrypt upper and lower case numbers specials chars:
      - run: python3 substitution.py decrypt
        stdin:
          - qwertyuiopasdfghjklzxcvbnm
          - Gjj3dS0. bcd$j3v14s-s33e
        stdout: Oqq3mL0. xvm$q3w14l-l33c
submit50:
  files: *check50_files
