check50:
  files: &check50_files
    - !exclude "*"
    - !include "substitution.py"
          
  checks:
    hello world:
      - run: python3 substitution.py encrypt
        stdin:
          - helloworld
          - qwertyuiopasdfghjklzxcvbnm
        stdout: pcssibidsm
    No Arguments:
      - run: python3 substitution.py 
        stdout: Usage substitution.py encrypt/decrypt
        exit: 1
    Too many arguments:
      - run: python3 substitution.py 2 3 5
        stdout: Too many arguments.
        exit: 1
    Key too short:
      - run: python3 substitution.py encrypt
        stdin: 
          - qwertyuasdf
        stdout: Invalid key length.
    Key too long:
      - run: python3 substitution.py encrypt
        stdin: 
          - qwertyuasdfqwertyuasdfqwertyuasdf
        stdout: Invalid key length.
    Duplicate letters in key:
      - run: python3 substitution.py encrypt 
        stdin: 
          - qwerty
          - qwertyuiopasdfghjklzxcvbnn
        stdout: Duplicate letters found in key.
    Accepts mixed case:
      - run: python3 substitution.py encrypt
        stdin:
          - HeLLoWorLD
          - qwertyuiopasdfghjklzxcvbnm
        stdout: PcSSiBidSM
    Accepts upper and lower case, numbers, specials chars:
      - run: python3 substitution.py encrypt
        stdin:
          - Upp3rL0. wer$p3c14l-l33t
          - qwertyuiopasdfghjklzxcvbnm
        stdout: Gjj3dS0. bcd$j3v14s-s33e
    Accepts mixedcase key:
      - run: python3 substitution.py encrypt
        stdin:
          - Hello123$
          - QWERTYUIOPasdfghjklZXCVBNM
        stdout: Pcssi123$
submit50:
  files: *check50_files
