check50:
  files: &check50_files
    - !exclude "*"
    - !include "substitution.py"
  
  checks:
    hello world:
      - run: python3 caesar.py
        stdin:
          - helloworld
          - 0
        stdout: helloworld
    hello shift 2:
      - run: python3 caesar.py 
        stdin: 
          - helloworld
          - 2
        stdout: jgnnqyqtnf
    Mix of upper and lowercase shift of 5:
      - run: python3 caesar.py 
        stdin: 
          - MiXoFuPpEr
          - 5
        stdout: RnCtKzUuJw
    Mix of upper and lowercase shift of 500:
      - run: python3 caesar.py 
        stdin: 
          - MiXoFuPpEr
          - 500
        stdout: SoDuLaVvKx
    Mix of upper and lowercase shift of neg5:
      - run: python3 caesar.py 
        stdin: 
          - NegativeShift
          - -5
        stdout: IzbvodqzNcdao
    Mix of upper lower specials chars:
      - run: python3 caesar.py 
        stdin: 
          - Upp3rL0. wer$p3c14l-l33t
          - 20
        stdout: Ojj3lF0. qyl$j3w14f-f33n
submit50:
  files: *check50_files
